import random
import json

# Extracted plant names from the provided list
plant_names = [
    "African sheepbush", "Alder", "Black alder", "Common alder", "False alder", "Gray alder", 
    "Speckled alder", "White alder", "Almond", "Aloe vera", "Amaranth", "Foxtail amaranth", 
    "Ambrosia", "Tall ambrosia", "Amy root", "Angel trumpet", "Apple", "Apricot", "Arfaj", 
    "Arizona sycamore", "Arrowwood", "Indian arrowwood", "Ash", "Black ash", "Blue ash", 
    "Cane ash", "European ash", "Green ash", "Maple ash", "Red ash", "River ash", "Swamp ash", 
    "White ash", "Water ash", "Azolla", "Carolina azolla", "Water Fern", "Bamboo", "Banana", 
    "Baobab", "Bay", "Bay laurel", "California bay", "Bean", "Bearberry", "Bear corn", "Beech", 
    "Bindweed", "Blue bindweed", "Bird's nest", "Bird's nest plant", "Bird of paradise", 
    "Birch", "Black birch", "Bolean birch", "Canoe birch", "Cherry birch", "European weeping birch", 
    "European white birch", "Gray birch", "Mahogany birch", "Paper birch", "Red birch", 
    "River birch", "Silver birch", "Spice birch", "Sweet birch", "Water birch", "Weeping birch", 
    "White birch", "Yellow birch", "Bittercress", "Hairy bittercress", "Bittersweet", 
    "Trailing bittersweet", "Bitterweed", "Blackberry", "Hispid swamp blackberry", 
    "Pennsylvania blackberry", "Running swamp blackberry", "Black cap", "Black-eyed Susan", 
    "Blackhaw", "Black-weed", "Blueberry", "Bluebell", "Blue-of-the-heavens", "Bola verde", 
    "Bow-wood", "Box", "False box", "Boxelder", "Boxwood", "False boxwood", "Brier", 
    "Sand brier", "Brittlebush", "Broadleaf", "Brown Betty", "Brown-eyed susan", 
    "Buckeye (California buckeye)", "Buckeye", "Buffalo weed", "Bugle", "Butterfly flower", 
    "Butterfly weed", "Beaked hazelnut", "Bottle tree", "Flame bottle tree", "Queensland bottle tree", 
    "Broad leaf bottle tree", "Cabbage", "Clumpfoot cabbage", "Meadow cabbage", "Skunk cabbage", 
    "Swamp cabbage", "California bay", "California buckeye", "California sycamore", 
    "California walnut", "Canada root", "Cancer jalap", "Carrot", "Wild carrot", "Carrot weed", 
    "Cart track plant", "Catalina ironwood", "Cedar", "Blue Atlas cedar", "Deodar cedar", 
    "Chalk milkwort", "Charlock", "Cherry", "Black cherry", "Cabinet cherry", "Rum cherry", 
    "Whiskey cherry", "Wild cherry", "Wild black cherry", "Chestnut", "Chigger flower", 
    "Chrysanthemum", "True cinnamon", "Clove", "Clover", "Coakum", "Coconut", "Coffee plant", 
    "Colic weed", "Collard", "Columbine", "Colwort", "Hare's colwort", "Comfrey", "Coneflower", 
    "Brilliant coneflower", "Cutleaf coneflower", "Eastern coneflower", "Green-headed Coneflower", 
    "Orange coneflower", "Tall coneflower", "Thin-leaved Coneflower", "Three-leaved Coneflower", 
    "Cornel", "Blueberry cornel", "Silky cornel", "White cornel", "Cornelian tree", "Corydalis", 
    "Fern-leaf Corydalis", "Golden corydalis", "Pale corydalis", "Pink corydalis", "Yellow corydalis", 
    "Cotton plant", "Creeping yellowcress", "Cress", "American cress", "Bank cress", 
    "Belle Isle cress", "Bermuda cress", "Bulbous cress", "Lamb's cress", "Land cress", 
    "Scurvy cress", "Spring cress", "Upland cress", "Crowfoot", "Crow's nest", "Crow's toes", 
    "Cucumber", "Daisy", "Brown daisy", "Common daisy", "Gloriosa daisy", "Poorland daisy", 
    "Yellow daisy", "Yellow ox-eye daisy", "Dandelion", "Deadnettle", "Henbit deadnettle", 
    "Red deadnettle", "Spotted deadnettle", "Desert Rose", "Devil's bite", "Devil's darning needle", 
    "Devil's nose", "Devil's plague", "Dewberry", "Bristly dewberry", "Swamp dewberry", "Dindle", 
    "Dogwood", "American dogwood", "Japanese flowering dogwood", "Drumstick", "Pacific dogwood", 
    "Silky dogwood", "Red osier dogwood", "Duck retten", "Duscle", "Durian", "Durian kura kura", 
    "Durian munjit", "Durian pulu", "Red durian", "Dye-leaves", "Dragon tree", "Dragons blood tree", 
    "Easter orchid", "Earth gall", "Elderberry", "Elegant lupine", "Elephant apple", 
    "English bull's eye", "Eucalyptus", "Evergreen huckleberry", "Extinguisher moss", "Eytelia", 
    "Fair-maid-of-France", "Fairymoss", "Fellenwort", "Felonwood", "Felonwort", "Fennel", "Ferns", 
    "Boston fern", "Christmas fern", "Coast polypody", "Kimberly queen fern", "Korean rock fern", 
    "Mosquito fern", "Sword ferns", "Water fern", "Western sword fern", "Feverbush", "Feverfew", 
    "Field forget-me-not", "Fig", "Common fig", "Flax", "European flax", "New Zealand flax", 
    "Fluxroot", "Foxglove", "Fumewort", "Yellow fumewort", "Gallberry", "Garget", "Garlic", 
    "Golden garlic", "Wild garlic", "Garlic mustard", "Garlic root", "Germander speedwell", 
    "Gilliflower", "Dame's gilliflower", "Night scented gilliflower", "Queen's gilliflower", 
    "Rogue's gilliflower", "Winter gilliflower", "Golden buttons", "Golden chain", "Goldenglow", 
    "Golden Jerusalem", "Gordaldo", "Goose tongue", "Grapefruit", "Grapevine", "Grass", 
    "Bermuda grass", "Green berry nightshade", "Groundberry", "Bristly groundberry", "Gutweed", 
    "Haldi", "Harlequin", "Rock harlequin", "Yellow harlequin", "Hay fever weed", "Healing blade", 
    "Hedge plant", "Hellebore", "American white hellebore", "Big hellebore", "Black hellebore", 
    "European white hellebore", "False hellebore", "Swamp hellebore", "White hellebore", "Hemp", 
    "Hemp dogbane", "Hemlock", "Hen plant", "Herb barbara", "Hogweed", "Holly", "Deciduous holly", 
    "European holly", "Inkberry holly", "Meadow holly", "Swamp holly", "Winterberry holly", 
    "Honesty", "Horse cane", "Horseradish", "Hound's berry", "Huckleberry", "Evergreen huckleberry", 
    "Trailing red huckleberry", "Houseleek", "Hydrangea", "Indian hemp", "White Indian hemp", 
    "Indian paintbrush", "Indian posy", "Inkberry", "Ironwood", "Isle of Man cabbage", "Itchweed", 
    "Ivy", "Jack-by-the-hedge", "Jack-in-the-bush", "Jasmine", "Jewel orchid", "Jointed rush", 
    "Jugflower", "Juneberry", "Juniper", "Keek", "King fern", "Kinnikinnik", "Kittentail", 
    "Knotweed", "Kousa", "Kudzu", "Kumarahou", "Lace Aloe", "Laceflower", "Lace fern", 
    "Lady's mantle", "Lady's smock", "Lamb's foot", "Latanier palm", "Laurel magnolia", "Lavender", 
    "Leek", "Lemon", "Leopard lily", "Lily of the Nile", "Lettuce", "Lily leek", "Lilac", 
    "Summer lilac", "Little sunflower", "Lone fleabane", "Love-lies-bleeding", "Love vine", 
    "Lupin", "Magnolia", "Bracken's Brown Beauty magnolia", "Galaxy magnolia", "Jane magnolia", 
    "Kay Parris magnolia", "Little Gem magnolia", "Moonglow magnolia", "Royal Star magnolia", 
    "Serendipity Ruby magnolia", "Southern magnolia", "Stellar Ruby magnolia", "Sweetbay magnolia", 
    "Waterlilly Star magnolia", "Maize", "Mango", "Maple", "Ash-leaved maple", "Black maple", 
    "Creek maple", "Cutleaf maple", "Moose maple", "Red river maple", "River maple", "Silver maple", 
    "Silverleaf maple", "Soft maple", "Striped maple", "Sugar maple", "Swamp maple", "Water maple", 
    "White maple", "Mesquite", "Honey mesquite", "Screwbean mesquite", "Milfoil", "Milkweed", 
    "Blunt-leaved Milkweed", "Common milkweed", "Horsetail milkweed", "Orange milkweed", 
    "Swamp milkweed", "Rose milkweed", "Whorled milkweed", "Yellow milkweed", "Milky tassel", 
    "Moosewood", "Petty morel", "Morelle verte", "Mosquito plant", "Mother-of-the-evening", 
    "Mountain mahogany", "Mulberry", "Red mulberry", "White mulberry", "Swiss Cheese Plant", 
    "Native fuchsia", "Necklace fern", "Neem", "Nettle", "Bull nettle", "Carolina horse nettle", 
    "Horse nettle", "Night-blooming cactus", "Nightshade", "American nightshade", "Bitter nightshade", 
    "Black nightshade", "Climbing nightshade", "Deadly nightshade", "Garden nightshade", 
    "Trailing nightshade", "Trailing violet nightshade", "Woody nightshade", "Nodding wakerobin", 
    "Northern moonwort", "Nosebleed", "Oak tree", "Algerian Oak", "Blue oak", "Bur oak", 
    "California Black Oak", "Canyon Live Oak", "Champion oak", "Coast live oak", "Cork oak", 
    "Dyer's oak", "Eastern black oak", "English oak", "Island oak", "Mirbeck's oak", 
    "Mossycup white oak", "Northern red oak", "Pedunculate oak", "Pin oak", "Red oak", "Scarlet oak", 
    "Scrub oak", "Sessile oak", "Spanish oak", "Spotted oak", "Swamp oak", "Swamp Spanish oak", 
    "Swamp white oak", "Valley oak", "White oak", "Yellowbark oak", "Obedient Plant", "Olive", 
    "Onion", "Common onion", "Giant onion", "Nodding onion", "Tree onion", "Wild onion", 
    "Osage orange", "Sweet orange", "Wild orange", "Orange-root", "Osage", "Osier", "Red osier", 
    "Parsley", "Parsnip", "Pawpaw", "Pea", "Peach", "Peanut", "Pear", "Pellitory", "Bastard pellitory", 
    "European pellitory", "Wild pellitory", "Penny hedge", "Pepper root", "Petty spurge", 
    "Pigeon berry", "Pine", "Aleppo pine", "Apache pine", "Austrian pine", "Black pine", 
    "Bosnian pine", "Canary Island pine", "Chinese red pine", "Chir pine", "Henry's pine", 
    "Huangshan pine", "Japanese red pine", "Khasi pine", "Loblolly pine", "Luchu pine", 
    "Maritime pine", "Masson's pine", "Merkus pine", "Mountain pine", "Red pine", "Scots pine", 
    "Sikang pine", "Stone pine", "Taiwan red pine", "Tenasserim pine", "Tropical pine", 
    "Turkish pine", "Yunnan pine", "Pineapple", "False pineapple", "Pineapple", "Pistachio", 
    "Atlas pistachio", "Chinese pistache", "Mexican pistache", "Persian turpentine tree", 
    "Pistachio", "Terebinth", "Zebrawood", "Plane", "Plantain", "Common plantain", "Sea plantain", 
    "Pleurisy root", "Poached egg plant", "Pocan bush", "Poison ivy", "Poisonberry", "Poisonflower", 
    "Poke", "Indian poke", "Pokeroot", "Pokeweed", "Polkweed", "Polecat weed", "Poor Annie", 
    "Poor man's mustard", "Poplar", "Poppy", "Possumhaw", "Potato", "Primrose", "Queen Anne's lace", 
    "Quercitron", "Radical weed", "Ragweed", "Common ragweed", "Giant ragweed", "Great ragweed", 
    "Ragwort", "Common ragwort", "Hoary ragwort", "Marsh ragwort", "Oxford ragwort", "Silver ragwort", 
    "Rantipole", "Rapeseed", "Raspberry", "Black raspberry", "Purple raspberry", "Redbrush", 
    "Redbud", "Eastern redbud", "Western redbud", "Judas-tree", "Red ink plant", "Redweed", 
    "Rheumatism root", "Rhubarb", "Ribwort", "Rice", "Asian rice", "African rice", "Roadweed", 
    "Rocket", "Dame's rocket", "Sweet rocket", "Winter rocket", "Yellow rocket", "Rocketcress", 
    "Rose", "Baby rose", "Dwarf wild rose", "Low rose", "Multiflora rose", "Prairie rose", 
    "Rambler rose", "Wild rose", "Rosemary", "Rye", "Saffron crocus", "Sanguinary", "Saskatoon", 
    "Sauce-alone", "Scarlet berry", "Scoke", "Scotch cap", "Scrambled eggs", "Scurvy grass", 
    "Serviceberry", "Common serviceberry", "Downy serviceberry", "Shadblow serviceberry", 
    "Shadblow", "Shadbush", "Shrubby mayweed", "Silkweed", "Swamp silkweed", "Virginia silkweed", 
    "Skunkweed", "Snakeberry", "Snowdrop", "Sorrel", "Redwood sorrel", "Speedwell", "Corn speedwell", 
    "Wall speedwell", "Spikenard", "Spoolwood", "Squaw bush", "Stammerwort", "Star-of-Persia", 
    "Stickweed", "Strawberry", "Strawberry tree", "Strawberry tree 'Marina'", "Sugarcane", 
    "Swallow-wort", "Orange swallow-wort", "Silky swallow-wort", "Sneezeweed", "Sneezewort", 
    "Sunflower", "Sugarplum", "Soldier's woundwort", "Stag bush", "Swallow-wort", "Orange swallow-wort", 
    "Silky swallow-wort", "Sweet potato", "Sweet potato vine", "Swinies", "Sycamore", 
    "Sycamore (California)", "Sycamore (Arizona)", "Sycamore (American)", "Sundari", "Gewa", 
    "Sunflower", "Stiff sunflower", "Lesser sunflower", "willow leaf sunflower", 
    "Stinking corpse flower", "Tansy", "Common tansy", "White tansy", "Wild tansy", "Tea", 
    "Appalachian tea", "Thimbleberry", "Thimbleweed", "Thousand-leaf", "Thousand-seal", 
    "Tassel weed", "Thistle", "Annual sow thistle", "California thistle", "Canada thistle", 
    "Corn thistle", "Corn sow thistle", "Creeping thistle", "Cursed thistle", "Field sow thistle", 
    "Green thistle", "Hard thistle", "Hare's thistle", "Milk thistle", "Nodding thistle", 
    "Perennial thistle", "Prickly thistle", "Sharp-fringed sow Thistle", "Small-flowered Thistle", 
    "Spiny sow thistle", "Spiny-leaved sow Thistle", "Swine thistle", "Tree sow thistle", 
    "Way thistle", "Thyme", "Tickleweed", "Tobacco plant", "Tomato", "Toothwort", "Cutleaf toothwort", 
    "Purple-flowered Toothwort", "Touch-me-not", "Traveller's joy", "Tread-softly", "Tree tobacco", 
    "Trillium", "Western trillium", "Western wake robin", "White trillium", "Tuber-root", "Tulip", 
    "Candia tulip", "Tulsi", "Umbrella palm", "Umbrella papyrus", "Vanilla orchid", "Varnish tree", 
    "Velvet bean", "Viburnum", "Blackhaw viburnum", "Leatherleaf viburnum", "Violet", 
    "African violet", "Damask violet", "Dame's violet", "Dog's-tooth-violet", "Violet bloom", 
    "Viper's grass", "Virgin's bower", "Virginia virgin's bower", "Voodoo lily", "Walnut", 
    "Wattle", "Mount Connor wattle", "Waybread", "Weed", "Western redbud", "Wheat", 
    "White man's foot", "White-root", "Wild cotton", "Wild honeysuckle", "Prickly honeysuckle", 
    "Heath-leaved honeysuckle", "Fairall's honeysuckle", "Mountain devil", "Honey flower", 
    "Holly-leaved honeysuckle", "Chittick", "Many-flowered honeysuckle", "Round-leaf honeysuckle", 
    "Green honeysuckle", "Wild hops", "Willow", "Coyote willow", "Goodding willow", "Red willow", 
    "Rose willow", "Windroot", "Wineberry", "Winterberry", "American winterberry", 
    "Evergreen winterberry", "Virginia winterberry", "Wintercress", "Early wintercress", 
    "Woodbine", "Woolly morning glory", "Wormwood", "Roman wormwood", "Wound rocket", 
    "Wolfsbane", "Chinese wolfsbane", "healing wolfsbane", "Yarrow", "Common yarrow", 
    "Fernleaf yarrow", "Sneezewort yarrow", "Woolly yarrow", "Yellow fieldcress", "Yellowwood", 
    "Yellow coneflower", "Yam", "Yunnan camellia", "Zebrawood", "Zedoary"
]

def generate_entry(plant_id, plant_name):
    soil_types = ["Sandy", "Clay", "Silt", "Peat", "Chalk", "Loam"]
    fertilizer_types = ["Organic", "Inorganic", "Compost", "Manure", "Liquid"]
    countries = ["USA", "Canada", "Germany", "Australia", "India", "Brazil", "Japan", "South Africa", "France", "Italy"]

    return {
        "Plant-ID": plant_id,
        "Plant-Rating": random.randint(1, 5),
        "Plant-Name": plant_name,
        "Soil-Type": random.choice(soil_types),
        "Sunlight-Hours": random.randint(1, 12),
        "Water-Frequency": random.choice(["Daily", "Weekly", "Bi-weekly", "Monthly"]),
        "Fertilizer-Type": random.choice(fertilizer_types),
        "Temperature": random.uniform(15.0, 35.0),  # Temperature in Celsius
        "Humidity": random.uniform(30.0, 80.0),     # Humidity in percentage
        "Location": f"{random.choice(countries)}",
        "Age": random.randint(1, 100)  # Age in weeks
    }

def generate_data(plant_names):
    data = [generate_entry(i, plant_names[i - 1]) for i in range(1, len(plant_names) + 1)]
    return data

def save_to_file(data, filename):
    with open(filename, 'w') as f:
        for entry in data:
            f.write(json.dumps(entry) + "\n")

# Generate entries for the provided plant names
data = generate_data(plant_names)
save_to_file(data, 'dynamodb_data.json')

print("Data file generated successfully.")
