environmentTag:
  dev: "Dev-Dev"
  # hmd: "Test-Hmd"
  # qa: "Test-QA"
  # qa2: "Test-QA2"
  # qa3: "Test-QA3"
  # qa4: "Test-QA4"
  # sit: "Test-SIT"
  # pat: "Test-PAT"
  # staging: "Test-Staging"
  # prod: "Prod-Prod"
  # other: "Dev-${opt:stage}"
  # and: "Dev-Andrei"
  # rzv: "Dev-Razvan"
  # iul: "Dev-Iulian"
