CMKSecretsManager:
  Type: AWS::KMS::Key
  Properties:
    Description: CMK used for the Cavendish-${self:provider.stage} Secrets encryption
    MultiRegion: false
    EnableKeyRotation: true
    PendingWindowInDays: 7
    KeyPolicy:
      Version: '2012-10-17'
      Id: cmk-secretsmanager-${self:provider.stage}
      Statement:
      - Sid: Enable IAM User Permissions  # TODO: to be removed
        Effect: Allow
        Principal:
          AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
        Action: kms:*
        Resource: '*'
      - Sid: Allow access for Key Administrators
        Effect: Allow
        Principal:
          AWS:
          # - !Sub 'arn:aws:iam::${AWS::AccountId}:role/KMSAdmin'
          - !Sub 'arn:aws:iam::${AWS::AccountId}:user/${self:custom.vars.aws-devops-user.${self:custom.stage}, self:custom.vars.aws-devops-user.other}'
        Action:
        - kms:Create*
        - kms:Describe*
        - kms:Enable*
        - kms:List*
        - kms:Put*
        - kms:Update*
        - kms:Revoke*
        - kms:Disable*
        - kms:Get*
        - kms:Delete*
        - kms:TagResource
        - kms:UntagResource
        - kms:ScheduleKeyDeletion
        - kms:CancelKeyDeletion
        Resource: '*'
      - Sid: Enable SecretsManager use of the key
        Effect: Allow
        Principal:
          AWS: "*"
        Action:
        - kms:Decrypt
        Resource: "*"
        Condition:
          StringEquals:
            kms:CallerAccount: !Ref AWS::AccountId
            kms:ViaService: !Sub 'secretsmanager.${AWS::Region}.amazonaws.com'
