FootballGamesTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:service}_${self:provider.stage}_football-games
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: N
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    BillingMode: PAY_PER_REQUEST
    StreamSpecification:
      StreamViewType: NEW_AND_OLD_IMAGES
    SSESpecification:
      SSEEnabled: true
      SSEType: KMS
      KMSMasterKeyId: !Ref CMKDynamoDB
